name: Build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install Dependencies
        run: composer install

      - name: Build Binary
        run: php nebula app:build --build-version=${{ github.ref_name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nebula-${{ github.ref_name }}
          path: builds/nebula
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: builds/nebula/*
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
