name: Build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2

      - name: Install dependencies
        run: composer install

      - name: Build
        run: php nebula app:build --build-version=${GITHUB_REF#refs/tags/}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nebula-${GITHUB_REF#refs/tags/}
          path: builds/nebula
      